# Generated by Django 3.0.8 on 2020-07-31 11:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Register1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_first_name', models.CharField(max_length=100)),
                ('d_last_name', models.CharField(max_length=100)),
                ('d_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('d_password1', models.CharField(max_length=100)),
                ('d_password2', models.CharField(max_length=100)),
                ('d_email', models.EmailField(max_length=254)),
                ('d_aadhar', models.IntegerField()),
                ('d_license_number', models.IntegerField()),
                ('d_gender', models.CharField(max_length=200)),
                ('d_qualification', models.CharField(max_length=100)),
                ('d_specialization', models.CharField(max_length=100)),
                ('d_practice', models.CharField(max_length=100)),
                ('d_img', models.ImageField(upload_to='pics')),
                ('d_age', models.IntegerField()),
                ('d_address', models.CharField(max_length=500)),
                ('d_city', models.CharField(max_length=100)),
                ('d_state', models.CharField(max_length=100)),
                ('d_postal', models.IntegerField()),
                ('d_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Med_tab1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_level1', models.CharField(max_length=10)),
                ('m_name1', models.CharField(max_length=100)),
                ('m_is_antibiotic1', models.CharField(max_length=100)),
                ('m_for_infection1', models.CharField(max_length=100)),
                ('m_dose1', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Register1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_first_name', models.CharField(max_length=100)),
                ('p_last_name', models.CharField(max_length=100)),
                ('p_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('p_password1', models.CharField(max_length=100)),
                ('p_password2', models.CharField(max_length=100)),
                ('p_gender', models.CharField(max_length=10)),
                ('p_age', models.IntegerField()),
                ('p_email', models.EmailField(max_length=254)),
                ('p_weight', models.IntegerField()),
                ('p_bloodgrp', models.CharField(max_length=100)),
                ('p_aadhar', models.IntegerField()),
                ('p_img', models.ImageField(upload_to='pics')),
                ('p_address', models.CharField(max_length=1024)),
                ('p_city', models.CharField(max_length=100)),
                ('p_state', models.CharField(max_length=100)),
                ('p_postal', models.IntegerField()),
                ('p_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_day', models.CharField(max_length=100)),
                ('t_date', models.DateField()),
                ('t_time', models.TimeField()),
                ('d_uid', models.IntegerField()),
                ('p_uid', models.IntegerField()),
                ('p_caseno', models.IntegerField()),
                ('p_name', models.CharField(max_length=100)),
                ('p_age', models.IntegerField()),
                ('p_gender', models.CharField(max_length=100)),
                ('p_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Treatment_Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_uid', models.IntegerField()),
                ('p_uid', models.IntegerField()),
                ('p_caseno', models.IntegerField()),
                ('p_infection', models.CharField(max_length=100)),
                ('p_symptoms', models.CharField(max_length=100)),
                ('p_weight', models.IntegerField()),
                ('p_bp', models.CharField(max_length=100)),
                ('p_diagnosis', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Treatment_Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_uid', models.IntegerField()),
                ('p_caseno', models.IntegerField()),
                ('p_medicine', models.CharField(max_length=100)),
                ('p_med_duration', models.IntegerField()),
                ('p_med_morning', models.CharField(max_length=10)),
                ('p_med_afternoon', models.CharField(max_length=10)),
                ('p_med_night', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sih_abstrix_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_first_name', models.CharField(max_length=100)),
                ('a_last_name', models.CharField(max_length=100)),
                ('a_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('a_password1', models.CharField(max_length=100)),
                ('a_password2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
