# Generated by Django 3.0.8 on 2020-08-01 16:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_register1',
            name='d_aadhar',
        ),
        migrations.AlterField(
            model_name='doctor_register1',
            name='d_license_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
