# Generated by Django 3.0.8 on 2020-08-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp1', '0002_auto_20200801_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_register1',
            old_name='p_country',
            new_name='p_unique_id',
        ),
        migrations.RemoveField(
            model_name='doctor_register1',
            name='d_practice',
        ),
        migrations.RemoveField(
            model_name='patient_register1',
            name='p_aadhar',
        ),
        migrations.RemoveField(
            model_name='patient_register1',
            name='p_address',
        ),
        migrations.RemoveField(
            model_name='patient_register1',
            name='p_email',
        ),
        migrations.RemoveField(
            model_name='patient_register1',
            name='p_first_name',
        ),
        migrations.RemoveField(
            model_name='patient_register1',
            name='p_img',
        ),
        migrations.RemoveField(
            model_name='patient_register1',
            name='p_last_name',
        ),
        migrations.RemoveField(
            model_name='patient_register1',
            name='p_number',
        ),
        migrations.RemoveField(
            model_name='patient_register1',
            name='p_password1',
        ),
        migrations.RemoveField(
            model_name='patient_register1',
            name='p_password2',
        ),
        migrations.RemoveField(
            model_name='patient_register1',
            name='p_postal',
        ),
        migrations.RemoveField(
            model_name='patient_register1',
            name='p_weight',
        ),
    ]
