# Generated by Django 3.0.8 on 2020-08-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp1', '0003_auto_20200801_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_treatment',
            name='p_name',
        ),
        migrations.RemoveField(
            model_name='patient_treatment',
            name='p_number',
        ),
    ]
