# Generated by Django 3.0.8 on 2020-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp1', '0004_auto_20200801_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_register1',
            name='d_license_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor_register1',
            name='d_number',
            field=models.BigIntegerField(),
        ),
    ]
