# Generated by Django 3.0.8 on 2020-08-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp1', '0006_sih2020data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_treatment',
            old_name='p_uid',
            new_name='p_unique_id',
        ),
        migrations.AddField(
            model_name='patient_treatment',
            name='p_bloodgrp',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_treatment',
            name='p_city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_treatment',
            name='p_state',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
