# Generated by Django 3.0.8 on 2020-08-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp1', '0007_auto_20200802_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_treatment_diagnosis',
            name='p_uid',
        ),
        migrations.RemoveField(
            model_name='patient_treatment_medicines',
            name='p_uid',
        ),
        migrations.AddField(
            model_name='patient_treatment_diagnosis',
            name='p_unique_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_treatment_medicines',
            name='p_unique_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient_treatment',
            name='p_unique_id',
            field=models.CharField(max_length=100),
        ),
    ]
